### Health check
GET http://localhost:8008/dbhealth

### Database test
GET http://localhost:8008/api/pullusers

### Register a user
POST http://localhost:8008/api/adduser
Content-Type: application/json

{
  "email": "testomundo@example.com",
  "username": "testomundo",
  "password": "password1337"
}
### Check login
POST http://localhost:8008/api/login
Content-Type: application/json

{
  "username": "testuser",
  "password": "password123"
}

POST http://localhost:8008/api/addtask
Content-Type: application/json
{
  "goalid": 1,
  "title": "the testing of the server",
  "description": "And lo! did the programmer test the server",
  "due_date": "2026-01-01 12:00:00"
}

POST http://localhost:8008/api/addgoal
Content-Type: application/json
{
  "userid": 1,
  "title": "this is a test",
  "description": "this is a test of the mundo!"
}